version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.vidi9aug2.integrations:Test1
  packages:
  - name: EdgeVidi9Aug2
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.451
packages:
- name: EdgeVidi9Aug2
  gitServerName: vidi9Aug
  gitUrl: https://github.com/vijetadixit/EdgeVidi9Aug2
  gitUsername: vijetadixit
  gitToken: edge.scaffolding.EdgeVidi9Aug2.vidi9Aug.gitToken
  gitBranch: Master
